name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          python -m pip install -U pip
          pip install pytest

      - name: Build and Run Tests
        run: pytest -vvv --junitxml=pytest.xml

      # - name: Publish Test Report
        # uses: mikepenz/action-junit-report@v2
        # with:
          # report_paths: 'pytest.xml'

      # - name: Test Report
        # uses: dorny/test-reporter@v1
        # if: success() || failure()
        # with:
          # name: Java Tests
          # path: pytest.xml
          # reporter: java-junit

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: pytest.xml
